Add fractional cover
SatelliteApplicationsCatapult/odc-product-docker-images pull request #2
Opened 2020-04-15 14:47 UTC by dtip

Notes:
* `product` here is the geomedian annual summary product
* The way dask chunk size is defined for geomedian isn't granular enough for fractional cover - we want to be able to set a size for the `time` chunk as well as x and y.
* I've accidentally formatted the geomedian script with Black. Let me know if you don't like this and I'll undo.
* This script is quite different to the on-demand fractional cover generation script. I think it makes sense not to try to combine the two.

Things I'm not sure about:
* The product definition for geomedian gives nodata=-9999 but the geomedian script gives nodata=0. The fractional cover definition/script copies this. Is this correct?
* Should I be adding some job examples?
* Not 100% certain about the product definitions I've added but Sarah has volunteered to check

2020-04-15 15:06 UTC, sarah-cheesbrough requested changes
Review on Yaml creation

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +        name: blue
The output of the fractional cover script won't be a product with blue, green, red bands etc. The output is a 3band raster with bands named 'pv' (photosynthetic vegetation), 'npv' (non-photosynthetic vegetation) and 'bs' (bare soil). 

So for each sensor there should be three measurements:
change 'red' to 'pv'
change 'green' to 'npv'
change 'blue' to 'bs'

Then remove measurements of swir1, swir2, nir. 
Does this make sense - should line up with what comes out of the script.

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +        name: blue
change to bs

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +        name: green
chagne to npv

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +        name: red
change to pv

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +        name: nir
delete this measurement

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +        name: swir1
delete this measurement

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +        name: swir2
delete this measurement

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +name: ls7_fractional_cover_annual
repeat changes to ls7 as applied to ls8

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +name: ls5_fractional_cover_annual
repeat changes applied to ls8 to ls5

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +name: ls4_fractional_cover_annual
repeat changes to ls4 as to ls8

2020-04-15 15:06 UTC, sarah-cheesbrough commented on datacube-product-definitions/s2_fractional_cover_annual.yaml
> +name: s2_fractional_cover_annual
changers as to ls8 to s2

2020-04-15 15:13 UTC, sarah-cheesbrough commented
'The product definition for geomedian gives nodata=-9999 but the geomedian script gives nodata=0. The fractional cover definition/script copies this. Is this correct?'

In response to this, I think it would be best to have consistency with nodata values,

I'm a little confused by what you say the current status is. Do you mean the geomedian product has a nodata value of -9999, but the fractional cover a nodata value of 0? We should avoid a nodata value for the fractional cover of 0 as this is a legitimate value for each of the three fractional cover bands.

2020-04-15 15:17 UTC, dtip commented
Yeah that wasn't a clear comment. I've updated it.

What I mean is: the product definition for S2 data for geomedian gives nodata as -9999. But if you check geomedian.py, we use nodata=0 for S2 data (LS uses nodata=-9999).

I'll update the fractional cover script to use nodata=-9999 everywhere.

2020-04-15 15:22 UTC, dtip commented on datacube-product-definitions/ls_fractional_cover_annual.yaml
> +        name: blue
Great catch. I've made the changes

2020-04-15 15:37 UTC, dtip commented
@luigidifraia Could you explain why we're using nodata=0 for Sentinal 2 geomedian data?

2020-04-20 07:27 UTC, luigidifraia approved these changes

2020-04-20 07:28 UTC, merged